name = "uptin-ws"
workers_dev = true
compatibility_date = "2023-03-06"
main = "worker.mjs"

[durable_objects]
durable_objects_persist = true
cache_persist = true
bindings = [
  { name = "rooms", class_name = "Room" },
]

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

# Indicate that you want the Room classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Room"]